dist: xenial
language: python
python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt

# command to run tests
script:
  - py.test -v tests/  --doctest-modules --cov mqtt-forger --cov-report term-missing

after_success:
  - coveralls